/// Flutter icons HatIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HatIcon
///      fonts:
///       - asset: fonts/HatIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HatIcon {
  HatIcon._();

  static const _kFontFam = 'HatIcon';
  static const String? _kFontPkg = null;

  static const IconData fill =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stroke =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
